version: '3.7'
services:
  mongo1:
    image: mongo:4.2
    container_name: mongo1
    command: ["--replSet", "rs0", "--port", "2717"]
    volumes:
      - mongodb-data:/data/mongos/db1
    ports:
      - 2717:2717
  mongo2:
    image: mongo:4.2
    container_name: mongo2
    command: ["--replSet", "rs0", "--port", "2727"]
    volumes:
      - mongodb-data:/data/mongos/db2
    ports:
      - 2727:2727
  mongo3:
    image: mongo:4.2
    container_name: mongo3
    command: ["--replSet", "rs0", "--port", "2737"]
    volumes:
      - mongodb-data:/data/mongos/db3
    ports:
      - 2737:2737
  server:
    container_name: igbo_api_server
    restart: always
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo1
      - mongo2
      - mongo3
volumes: 
  mongodb-data: